alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias ls='ls -F --color=auto'
alias ll='ls -lFh'
alias la='ls -Ah'
alias li='ls -ialFh'
alias lsd='ls -ld *(-/DN)'
alias lsa='ls -ld .*'
alias l='ls -CF'
alias less='less -M'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias envset='source ~/bin/env.sh'
alias minicom='minicom -con'
alias gk='gitk --max-count=100 --all'
alias fucking=sudo
